
## Configuracion de Spring
spring:
  application:
    name: cuenta-movimiento
  datasource:
    url: jdbc:postgresql://localhost:5433/prueba
    username: postgres
    password: conejoej7
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
## Configuracion de Instancia
server:
  port: 8089
